<?php


namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'Indomie Goreng',
                'description' => 'Mi instan rasa goreng spesial.',
                'price' => 3000,
                'stock' => 120,
                'image_path' => 'images/product/indomie.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Gulaku Gula Tebu',
                'description' => 'Gula tebu premium ukuran 1 kg.',
                'price' => 15000,
                'stock' => 80,
                'image_path' => 'images/product/gulaku.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Minyak Goreng',
                'description' => 'Minyak goreng 2 liter dari bahan kelapa sawit pilihan.',
                'price' => 28000,
                'stock' => 60,
                'image_path' => 'images/product/minyak.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Kaos Batik Modern',
                'description' => 'Kaos motif batik kombinasi katun nyaman untuk sehari-hari.',
                'price' => 85000,
                'stock' => 45,
                'image_path' => 'images/product/kaos-batik.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Kemeja Tenun Ikat',
                'description' => 'Kemeja tenun ikat handmade dari pengrajin lokal.',
                'price' => 165000,
                'stock' => 30,
                'image_path' => 'images/product/kemeja-tenun.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Keripik Singkong Balado',
                'description' => 'Keripik singkong renyah rasa balado pedas manis.',
                'price' => 18000,
                'stock' => 150,
                'image_path' => 'images/product/keripik-singkong.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Kopi Arabika Premium 250g',
                'description' => 'Biji kopi arabika pilihan dengan aroma fruity dan rasa seimbang.',
                'price' => 75000,
                'stock' => 60,
                'image_path' => 'images/product/kopi-arabika-premium.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Teh Hijau Sencha',
                'description' => 'Teh hijau sencha khas Jepang dengan rasa segar dan menenangkan.',
                'price' => 52000,
                'stock' => 80,
                'image_path' => 'images/product/teh-hijau-sencha.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Granola Tropical Mix',
                'description' => 'Granola crunchy dengan campuran buah tropis kering dan kacang-kacangan.',
                'price' => 68000,
                'stock' => 70,
                'image_path' => 'images/product/granola-tropical.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Susu Almond Original 1L',
                'description' => 'Susu almond tanpa gula tambahan, cocok untuk gaya hidup sehat.',
                'price' => 49000,
                'stock' => 90,
                'image_path' => 'images/product/susu-almond-original.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Jus Cold Pressed Berry',
                'description' => 'Jus cold pressed dari campuran stroberi, blueberry, dan raspberry.',
                'price' => 38000,
                'stock' => 85,
                'image_path' => 'images/product/jus-berry-cold-pressed.jpg',
                'category' => 'Makanan & Minuman',
            ],
            [
                'name' => 'Gelang Manik Kulit',
                'description' => 'Gelang handmade kombinasi kulit dan manik-manik kayu.',
                'price' => 32000,
                'stock' => 90,
                'image_path' => 'images/product/gelang-kulit.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Anting Kuningan Etnik',
                'description' => 'Anting kuningan etnik dengan sentuhan modern.',
                'price' => 27000,
                'stock' => 75,
                'image_path' => 'images/product/anting-kuningan.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Jam Tangan Kulit Minimalis',
                'description' => 'Jam tangan analog dengan strap kulit asli dan desain minimalis elegan.',
                'price' => 215000,
                'stock' => 40,
                'image_path' => 'images/product/jam-kulit-minimalis.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Kacamata Hitam Classic',
                'description' => 'Kacamata hitam model wayfarer dengan lensa UV400.',
                'price' => 185000,
                'stock' => 55,
                'image_path' => 'images/product/kacamata-classic.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Topi Bucket Denim',
                'description' => 'Topi bucket berbahan denim yang nyaman untuk aktivitas luar ruangan.',
                'price' => 68000,
                'stock' => 65,
                'image_path' => 'images/product/topi-bucket-denim.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Tas Kanvas Tote Urban',
                'description' => 'Tas tote kanvas dengan kantong dalam dan desain urban modern.',
                'price' => 125000,
                'stock' => 50,
                'image_path' => 'images/product/tas-kanvas-urban.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Gantungan Kunci Resin Floral',
                'description' => 'Gantungan kunci resin dengan motif bunga kering yang unik.',
                'price' => 28000,
                'stock' => 120,
                'image_path' => 'images/product/gantungan-resin-floral.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Dompet Kulit Slim',
                'description' => 'Dompet kulit tipis dengan banyak slot kartu dan kompartemen uang kertas.',
                'price' => 165000,
                'stock' => 70,
                'image_path' => 'images/product/dompet-kulit-slim.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Set Scrunchie Satin',
                'description' => 'Paket tiga scrunchie satin lembut yang ramah untuk rambut dan nyaman dipakai.',
                'price' => 42000,
                'stock' => 95,
                'image_path' => 'images/product/scrunchie-satin-set.jpg',
                'category' => 'Aksesoris',
            ],
            [
                'name' => 'Notebook Daur Ulang',
                'description' => 'Buku catatan dengan kertas daur ulang ramah lingkungan.',
                'price' => 28000,
                'stock' => 110,
                'image_path' => 'images/product/notebook-daur-ulang.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Paket Pena Kayu',
                'description' => 'Set pena kayu ukir dengan tinta isi ulang.',
                'price' => 54000,
                'stock' => 65,
                'image_path' => 'images/product/pena-kayu.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Lampu Meja Kayu',
                'description' => 'Lampu meja dengan kaki kayu jati dan kap anyaman.',
                'price' => 150000,
                'stock' => 25,
                'image_path' => 'images/product/lampu-kayu.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Speaker Mini Bambu',
                'description' => 'Speaker bluetooth portable dengan casing bambu.',
                'price' => 185000,
                'stock' => 40,
                'image_path' => 'images/product/speaker-bambu.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Serum Wajah Herbal',
                'description' => 'Serum wajah alami dengan kandungan lidah buaya dan vitamin C.',
                'price' => 99000,
                'stock' => 70,
                'image_path' => 'images/product/serum-herbal.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Lulur Kopi Nusantara',
                'description' => 'Scrub tubuh dari bubuk kopi dan minyak kelapa.',
                'price' => 45000,
                'stock' => 85,
                'image_path' => 'images/product/lulur-kopi.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Pensil Mekanik 0.5mm',
                'description' => 'Pensil mekanik dengan grip empuk untuk menulis dan menggambar.',
                'price' => 12000,
                'stock' => 45,
                'image_path' => 'images/product/pensil-mekanik.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Buku Binder A5',
                'description' => 'Buku binder ukuran A5 dengan ring kuat dan isi ulang kertas bergaris.',
                'price' => 28000,
                'stock' => 30,
                'image_path' => 'images/product/binder-a5.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Rautan Pensil Otomatis',
                'description' => 'Rautan pensil otomatis mini dengan sisa rautan tertampung rapi.',
                'price' => 18000,
                'stock' => 25,
                'image_path' => 'images/product/rautan.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Gunting Kertas',
                'description' => 'Gunting stainless ukuran sedang untuk keperluan kantor dan sekolah.',
                'price' => 15000,
                'stock' => 40,
                'image_path' => 'images/product/gunting.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Penggaris Logam 30cm',
                'description' => 'Penggaris berbahan logam tahan lama dan akurat untuk gambar teknik.',
                'price' => 12000,
                'stock' => 30,
                'image_path' => 'images/product/penggaris-logam.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Stabilo Highlighter Pastel Set',
                'description' => 'Set stabilo warna pastel dengan ujung miring untuk highlight rapi di kertas.',
                'price' => 65000,
                'stock' => 55,
                'image_path' => 'images/product/stabilo-pastel-set.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Organizer Desk Multifungsi',
                'description' => 'Organizer meja berbahan akrilik transparan untuk menyimpan alat tulis.',
                'price' => 48000,
                'stock' => 70,
                'image_path' => 'images/product/organizer-desk-akrilik.jpg',
                'category' => 'Alat Tulis',
            ],
            [
                'name' => 'Powerbank 10000mAh',
                'description' => 'Powerbank slim dengan kapasitas 10000mAh dan fitur fast charging.',
                'price' => 185000,
                'stock' => 30,
                'image_path' => 'images/product/powerbank.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Headset Bluetooth',
                'description' => 'Headset nirkabel dengan suara jernih dan bass kuat.',
                'price' => 350000,
                'stock' => 25,
                'image_path' => 'images/product/headset.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Flashdisk 64GB',
                'description' => 'Flashdisk USB 3.0 kecepatan tinggi dengan kapasitas 64GB.',
                'price' => 95000,
                'stock' => 45,
                'image_path' => 'images/product/flashdisk-sandisk.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Adaptor Laptop Universal',
                'description' => 'Adaptor serbaguna kompatibel untuk berbagai merk laptop.',
                'price' => 180000,
                'stock' => 30,
                'image_path' => 'images/product/adaptor-universal.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Kipas Meja USB Mini',
                'description' => 'Kipas kecil bertenaga USB untuk meja kerja atau belajar.',
                'price' => 45000,
                'stock' => 40,
                'image_path' => 'images/product/kipaskecil.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Mouse Wireless Silent Click',
                'description' => 'Mouse nirkabel dengan desain ergonomis dan klik senyap untuk kerja kantor.',
                'price' => 125000,
                'stock' => 85,
                'image_path' => 'images/product/mouse-wireless-silent.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Charger GaN 65W Multi Port',
                'description' => 'Charger GaN dengan tiga port dan dukungan fast charging untuk laptop dan smartphone.',
                'price' => 325000,
                'stock' => 50,
                'image_path' => 'images/product/charger-gan-65w.jpg',
                'category' => 'Perlengkapan Elektronik',
            ],
            [
                'name' => 'Kaos Polos Katun Premium',
                'description' => 'Kaos polos berbahan katun premium yang lembut dan nyaman dipakai sehari-hari.',
                'price' => 75000,
                'stock' => 50,
                'image_path' => 'images/product/kaospolos.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Kemeja Flanel Pria',
                'description' => 'Kemeja flanel lengan panjang dengan motif kotak-kotak, cocok untuk tampilan kasual.',
                'price' => 120000,
                'stock' => 35,
                'image_path' => 'images/product/kemejaflanel.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Dress Wanita Casual',
                'description' => 'Dress wanita berbahan rayon yang ringan dan nyaman, cocok untuk acara santai.',
                'price' => 135000,
                'stock' => 25,
                'image_path' => 'images/product/dresswanita.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Jaket Denim Unisex',
                'description' => 'Jaket denim klasik dengan potongan unisex, cocok untuk gaya santai sehari-hari.',
                'price' => 185000,
                'stock' => 20,
                'image_path' => 'images/product/jaketdenim.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Celana Jeans Slim Fit',
                'description' => 'Celana jeans slim fit berbahan stretch, nyaman digunakan untuk kegiatan harian.',
                'price' => 160000,
                'stock' => 30,
                'image_path' => 'images/product/celanajeans.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Hoodie Oversized',
                'description' => 'Hoodie dengan desain oversized dan bahan fleece lembut, cocok untuk gaya kasual.',
                'price' => 145000,
                'stock' => 25,
                'image_path' => 'images/product/hoodieoversized.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Rok Plisket Midi',
                'description' => 'Rok plisket panjang dengan bahan ringan dan flowy, cocok untuk tampilan feminin.',
                'price' => 98000,
                'stock' => 28,
                'image_path' => 'images/product/rokplisket.jpg',
                'category' => 'Pakaian',
            ],
            [
                'name' => 'Lip Tint Natural Glow',
                'description' => 'Lip tint dengan warna natural dan tahan lama, memberikan hasil akhir glossy lembut.',
                'price' => 55000,
                'stock' => 60,
                'image_path' => 'images/product/liptint.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Serum Wajah Vitamin C',
                'description' => 'Serum pencerah wajah dengan kandungan Vitamin C tinggi untuk kulit cerah dan sehat.',
                'price' => 98000,
                'stock' => 45,
                'image_path' => 'images/product/serumvitaminc.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Facial Wash Aloe Vera',
                'description' => 'Pembersih wajah berbahan aloe vera yang menenangkan kulit dan menjaga kelembapan.',
                'price' => 43000,
                'stock' => 80,
                'image_path' => 'images/product/facialwashaloevera.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Sheet Mask Hydrating',
                'description' => 'Masker wajah berbahan hyaluronic acid yang melembapkan dan menyegarkan kulit.',
                'price' => 18000,
                'stock' => 100,
                'image_path' => 'images/product/sheetmask.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Bedak Tabur Matte Finish',
                'description' => 'Bedak tabur ringan untuk hasil matte alami dan tahan lama, cocok untuk semua jenis kulit.',
                'price' => 52000,
                'stock' => 40,
                'image_path' => 'images/product/bedakmatte.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Hand Body Lotion Sakura',
                'description' => 'Lotion tubuh dengan ekstrak bunga sakura yang melembapkan dan memberi aroma segar.',
                'price' => 67000,
                'stock' => 55,
                'image_path' => 'images/product/handbodylotion.jpg',
                'category' => 'Kecantikan',
            ],
            [
                'name' => 'Eyebrow Pencil Waterproof',
                'description' => 'Pensil alis tahan air dengan ujung lembut dan warna natural untuk tampilan alis sempurna.',
                'price' => 48000,
                'stock' => 65,
                'image_path' => 'images/product/eyebrowpencil.jpg',
                'category' => 'Kecantikan',
            ],



        ];

        foreach ($items as $item) {
            $category = Category::firstWhere('name', $item['category']);

            Product::updateOrCreate(
                ['name' => $item['name']],
                [
                    'description' => $item['description'],
                    'price' => $item['price'],
                    'stock' => $item['stock'],
                    'image_path' => $item['image_path'],
                    'category_id' => $category?->id,
                    'is_active' => true,
                ]
            );
        }
    }
}
